services:
  prisma-sase-5g:
    image: jsuzanne/prisma-5g-sase:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-sase-5g
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

